emulators/snes9x: unbreak with libc++ 3.9
unix/unix.cpp:1451:9: error: cannot initialize a variable of type 'char *' with an rvalue of type
      'const char *'
  char *slash = strrchr(path, SLASH_CHAR);
        ^       ~~~~~~~~~~~~~~~~~~~~~~~~~
unix/unix.cpp:1452:9: error: cannot initialize a variable of type 'char *' with an rvalue of type
      'const char *'
  char *dot = strrchr(path, '.');
        ^     ~~~~~~~~~~~~~~~~~~

PR:		212343
Regressed by:	https://github.com/llvm-mirror/libcxx/commit/b4aa97130b8b


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@430522 35697150-7ecd-e111-bb59-0022644237b5