- convert flask ports to USES=python - limit python version to 2 for www/py-flask-flatpages because of:
===>  Configuring for py34-Flask-FlatPages-0.5_1
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 10, in <module>
    INIT_PY = open(os.path.join(ROOT, 'flask_flatpages', '__init__.py')).read()
  File "/usr/local/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 164: ordinal not in range(128)
*** Error code 1

Approved by:    portmgr (blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@374444 35697150-7ecd-e111-bb59-0022644237b5