Fix build with CRYPTOPP option enabled (missed in r477967) Bump PORTREVISON due to cryptopp shared library version increase
libtool: compile:  c++ -DHAVE_CONFIG_H -I. -I.. -DKVZ_DLL_EXPORTS -isystem /usr/local/include -O2 -pipe -fstack-protector -isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include -MT extras/crypto.lo -MD -MP -MF extras/.deps/crypto.Tpo -c extras/crypto.cpp  -fPIC -DPIC -o extras/.libs/crypto.o
extras/crypto.cpp:19:3: error: unknown type name 'byte'; did you mean 'CryptoPP::byte'?
  byte key[CryptoPP::AES::DEFAULT_KEYLENGTH];
  ^~~~
  CryptoPP::byte
/usr/local/include/cryptopp/config.h:237:23: note: 'CryptoPP::byte' declared here
typedef unsigned char byte;
                      ^

Pointy hat:	jhale
Reported by:	fluffy
Obtained from:	upstream commits


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@478042 35697150-7ecd-e111-bb59-0022644237b5