games/gzdoom: Fix 32-bit build after r501260 (update to 4.1.1)
The update from 3.7.2 -> 4.1.1 included some path restructuring in gzdoom,
particularly around rendering bits. A list of source files that need SSE
explicitly enabled for 32-bit architectures is included in
src/CMakeLists.txt -- this had not been updated post-restructuring, leading
to errors like:

error: always_inline function '_mm_cvtss_f32' requires target feature 'mmx',
but would be inlined into function 'AddLights' that is compiled without
support for 'mmx'

and failing the build. The patch being added updates the paths. It was
submitted for upstreaming and subsequently accepted here:

https://github.com/coelckers/gzdoom/pull/850

to appear in a release post-4.1.2.

Reported by:	pkg-fallout
Approved by:	koobs (ports), kevans (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@503173 35697150-7ecd-e111-bb59-0022644237b5