www/py-cherrypy-old: convert to USES=python
- convert to USES=python
- limit to python2 only:
  """
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "setup.py", line 65
      print s % (name, version, required_python_version)
          ^
  SyntaxError: invalid syntax
  """

Approved by:	portmgr (blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@371115 35697150-7ecd-e111-bb59-0022644237b5