CMake: Add upstream patch to fix the build with recent GCCs.
At least lang/gcc (4.8) and later were known to be broken like this:

/usr/ports/devel/cmake/work/cmake-3.4.0/Source/cmArchiveWrite.h:93:23: error: 'mode_t' has not been declared
   void SetPermissions(mode_t permissions_)
                       ^
/usr/ports/devel/cmake/work/cmake-3.4.0/Source/cmArchiveWrite.h:106:27: error: 'mode_t' has not been declared
   void SetPermissionsMask(mode_t permissionsMask_)
                           ^
/usr/ports/devel/cmake/work/cmake-3.4.0/Source/cmArchiveWrite.h:179:26: error: 'mode_t' was not declared in this scope
   cmArchiveWriteOptional<mode_t> Permissions;
                          ^
/usr/ports/devel/cmake/work/cmake-3.4.0/Source/cmArchiveWrite.h:179:32: error: template argument 1 is invalid
   cmArchiveWriteOptional<mode_t> Permissions;
                                ^
/usr/ports/devel/cmake/work/cmake-3.4.0/Source/cmArchiveWrite.h:180:26: error: 'mode_t' was not declared in this scope
   cmArchiveWriteOptional<mode_t> PermissionsMask;
                          ^
/usr/ports/devel/cmake/work/cmake-3.4.0/Source/cmArchiveWrite.h:180:32: error: template argument 1 is invalid
   cmArchiveWriteOptional<mode_t> PermissionsMask;
                                ^

This was introduced in CMake 3.4.0, so there is no need for an MFH request.

PR:		204921


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@402818 35697150-7ecd-e111-bb59-0022644237b5