- Fix runtime error:
Global symbol "@args" requires explicit package name at /usr/local/share/shutter/resources/modules/Shutter/App/HelperFunctions.pm line 56.
Global symbol "@args" requires explicit package name at /usr/local/share/shutter/resources/modules/Shutter/App/HelperFunctions.pm line 57.
Compilation failed in require at /usr/local/bin/shutter line 148.

See also: See also: https://bugs.launchpad.net/shutter/+bug/1495163/comments/2

- Bump PORTREVISION

Reviewed by:	feld
MFH:	2015Q3


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@398372 35697150-7ecd-e111-bb59-0022644237b5