Remove unused KeyIdTemplate variable from cms_common.c.
This fixes the build with GCC 6:
  cms_common.c:1668:31: error: 'KeyIdTemplate' defined but not used [-Werror=unused-const-variable=]

Note that the build is still broken on HEAD due to some macros being defined in
base's headers.

PR:		219275


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@448230 35697150-7ecd-e111-bb59-0022644237b5