Fix build on 9.x.
Adds compiler:c11 for this error:
sha1.h:80: error: static or type qualifiers in abstract declarator

dovecot no longer builds againt the old OpenSSL in 9.x base, so
require ssl from ports there.

Despite the dependency change (only for 9.x), I'm not bumping
PORTREVISION because build couldn't complete on 9.x regardless.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@418106 35697150-7ecd-e111-bb59-0022644237b5