math/py-graphillion: Update to 1.2
This version fixes build failures on FreeBSD versions that use Clang 6:

src/graphillion/zdd.cc:461:31: error: invalid operands to binary expression ('std::__1::ostream' (aka 'basic_ostream<char>') and 'std::__1::ostream')
  if (out == std::cout || out == std::cerr)
                          ~~~ ^  ~~~~~~~~~

Reported by:	pkg-fallout
MFH:		2018Q4


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@481437 35697150-7ecd-e111-bb59-0022644237b5