Fix build of the Qt interface on FreeBSD 10.2 and 10.3.  On FreeBSD 10.1, it builds without issue (and thats what I originally tested this on and assumed it would work on later releases), but there seems to be a regression in the c++ headers that appears to have happend in r278724, so use libc++ from ports.
libtool: compile:  c++ -std=c++11 -DHAVE_CONFIG_H -I. -I../../..
-I../../../lang/cpp/src -I../../../src -I/usr/local/include/qt5/QtCore
-I/usr/local/include/qt5 -fpic -I/usr/local/include -I/usr/local/include
-DBUILDING_QGPGME -isystem /usr/local/include -O2 -pipe -fstack-protector
-isystem /usr/local/include -fno-strict-aliasing -isystem /usr/local/include
-MT qgpgmeencryptjob.lo -MD -MP -MF .deps/qgpgmeencryptjob.Tpo -c
qgpgmeencryptjob.cpp  -fPIC -DPIC -o .libs/qgpgmeencryptjob.o
qgpgmeencryptjob.cpp:133:9: error: no matching function for call to 'bind'
    run(std::bind(&encrypt,
        ^~~~~~~~~
/usr/include/c++/v1/functional:2184:1: note: candidate template ignored:
couldn't infer template argument '_Fp'
bind(_Fp&& __f, _BoundArgs&&... __bound_args)
^
/usr/include/c++/v1/functional:2193:1: note: candidate template ignored:
couldn't infer template argument '_Rp'
bind(_Fp&& __f, _BoundArgs&&... __bound_args)
^
1 error generated.
gmake[4]: *** [Makefile:801: qgpgmeencryptjob.lo] Error 1

Also, link to libgpgmepp already installed instead of rebuilding it.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@424451 35697150-7ecd-e111-bb59-0022644237b5