www/cppcms: switch to C++11, required by ICU >= 59
In file included from /wrkdirs/usr/ports/www/cppcms/work/cppcms-1.0.5/booster/lib/locale/src/encoding/codepage.cpp:19:
In file included from /wrkdirs/usr/ports/www/cppcms/work/cppcms-1.0.5/booster/lib/locale/src/encoding/uconv_codepage.ipp:13:
In file included from /wrkdirs/usr/ports/www/cppcms/work/cppcms-1.0.5/booster/lib/locale/src/encoding/../icu/uconv.h:10:
/usr/local/include/unicode/unistr.h:3025:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text)) {}
      ^~~~~~~~~~~~~
/usr/local/include/unicode/unistr.h:3087:7: error: delegating constructors are permitted only in C++11
      UnicodeString(ConstChar16Ptr(text), length) {}
      ^~~~~~~~~~~~~
/usr/local/include/unicode/unistr.h:3180:7: error: delegating constructors are permitted only in C++11
      UnicodeString(Char16Ptr(buffer), buffLength, buffCapacity) {}
      ^~~~~~~~~~~~~

PR:		218788


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@449613 35697150-7ecd-e111-bb59-0022644237b5