games/openra: NUGET_PACKAGEDIR is a symlink after r460430
*.config files under thirdparty/download/ didn't have os="freebsd" lines
because find(1) doesn't follow symlinks by default which broke runtime e.g.,

System.DllNotFoundException: soft_oal.dll
  at (wrapper managed-to-native) OpenAL.ALC10:alcOpenDevice (string)
  at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor (System.String deviceName) [0x0003f] in <2342b54840fb4908bd25f1f5db2e89d7>:0
  at OpenRA.Platforms.Default.DefaultPlatform.CreateSound (System.String device) [0x00001] in <2342b54840fb4908bd25f1f5db2e89d7>:0
  at OpenRA.Sound..ctor (OpenRA.IPlatform platform, OpenRA.SoundSettings soundSettings) [0x0001d] in <e7e76c84784c4fac82f4d6ffd1656cc2>:0
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00223] in <e7e76c84784c4fac82f4d6ffd1656cc2>:0
System.DllNotFoundException: soft_oal.dll
  at (wrapper managed-to-native) OpenAL.ALC10:alcOpenDevice (string)
  at OpenRA.Platforms.Default.OpenAlSoundEngine..ctor (System.String deviceName) [0x0003f] in <2342b54840fb4908bd25f1f5db2e89d7>:0
  at OpenRA.Platforms.Default.DefaultPlatform.CreateSound (System.String device) [0x00001] in <2342b54840fb4908bd25f1f5db2e89d7>:0
  at OpenRA.Sound..ctor (OpenRA.IPlatform platform, OpenRA.SoundSettings soundSettings) [0x0001d] in <e7e76c84784c4fac82f4d6ffd1656cc2>:0
  at OpenRA.Game.Initialize (OpenRA.Arguments args) [0x00223] in <e7e76c84784c4fac82f4d6ffd1656cc2>:0


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@460436 35697150-7ecd-e111-bb59-0022644237b5