Require python version 2, because it dumps core with python3:
# collectd -f
Fatal Python error: no mem for sys.argv
ValueError: character U+6f633c00 is not in range [U+0000; U+10ffff]
Abort (core dumped)

Approved by:	maintainer


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@376888 35697150-7ecd-e111-bb59-0022644237b5