Update to 2.5.1
  * Add new USES: autoreconf, localbase, python, shebangfix
  * Mark broken on i386 --
       undefined reference to '__atomic_fetch_add_8'
  * Move libfstrm.so dependency so it is only added when the
    DNSTAP option is enabled.

PR:		220205
Submitted by:	freebsd@dns-lab.com (maintainer)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@444181 35697150-7ecd-e111-bb59-0022644237b5