Fix plist.
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: %%PYTHON_SITELIBDIR%%/vigra/fourier.so


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@449001 35697150-7ecd-e111-bb59-0022644237b5