www-beautitifulsoup: convert to USES=python
- convert to USES=python
- remove pkg-plist and limit py-beautifulsoup32 to python2:
  """
  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "setup.py", line 22
    print "Unit tests have failed!"
                                  ^
  SyntaxError: invalid syntax
  """

Approved by:	portmgr (blanket)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@371112 35697150-7ecd-e111-bb59-0022644237b5