- Update to version 0.9.2 and make it build on both amd64 and i386 by   defining __LONG_LONG_SUPPORTED macro, which allows to pull llabs(3)   for 64-bit numbers; was not a problem on amd64 because sizeof(long)   == 8 there and thus no `long long' help needed
- Bump required C++ standard to C++03; it's not quite ready for later
  ones due to the this:

    bardecode/code25i.hh:34:29: error: in-class initializer for static
    data member of type 'const double' requires 'constexpr' specifier

- GC no-op `post-extract' target, patches that were applied upstream,
  and no longer relevant libungif -> libgif fixups in the Makefile


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@500748 35697150-7ecd-e111-bb59-0022644237b5