Mark broken: Does not build
ocamlfind ocamlc  -thread -package lwt.ssl,lwt.extra,netstring,netsys,ssl,pcre,unix,dynlink,threads,findlib -I ../baselib -I ../http -I ../xmlp4 -I ../server -I ../extensions -I ../eliom -I +camlp4 -I +camlp4/Camlp4Parsers -o ocsigen -linkpkg -linkall camlp4lib.cma Camlp4OCamlRevisedParser.cmo Camlp4OCamlParser.cmo ../xmlp4/xhtml.cma ocsigen.cma server.cmo
File "_none_", line 1, characters 0-1:
Error: Error while linking server.cmo:
The external function `disable_nagle' is not available
gmake[1]: *** [ocsigen] Error 2
gmake[1]: Leaving directory `/wrkdirs/usr/ports/www/ocsigen/work/ocsigen-1.1.0/server'
gmake: *** [server.byte] Error 2
*** Error code 1

Reported by:	pkg-fallout since august 2013
With hat:	portmgr


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@342084 35697150-7ecd-e111-bb59-0022644237b5