Similar to bug 212465, lang/gcc5 doesn't compile with recent versions of libc++, because it attempts to redefine abort():
In file included from /wrkdirs/usr/ports/lang/gcc5/work/gcc-5.4.0/gcc/auto-profile.c:25:
In file included from /usr/include/c++/v1/map:446:
/usr/include/c++/v1/functional:1398:2: error: no member named 'fancy_abort' in namespace 'std::__1'; did you mean simply 'fancy_abort'?
        _VSTD::abort();
        ^~~~~~~
/usr/include/c++/v1/__config:383:15: note: expanded from macro '_VSTD'
#define _VSTD std::_LIBCPP_NAMESPACE
              ^

Patch this in the same way as the other gcc ports, by including <new> in
gcc/system.h, and moving a few includes to before "system.h".

Approved by:	gerald (maintainer)
PR:		216266
MFH:		2017Q1


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@432958 35697150-7ecd-e111-bb59-0022644237b5