sysutils/fusefs-pod: fix build with GCC-based architectures
Switch to GCC from ports on GCC architectures to fix linking and include strings.h in src/fusepod_util.h to find strcasecmp:
/usr/local/lib/libtag.so: undefined reference to `std::__cxx11::basic_string<wchar_t, std::char_traits<wchar_t>, std::allocator<wchar_t> >::find_last_not_of(wchar_t const*, unsigned long, unsigned long) const@GLIBCXX_3.4.21'

PR:		237157
Approved by:	mat (mentor), fjoe (maintainer timeout)
Differential Revision:	https://reviews.freebsd.org/D20113


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@500598 35697150-7ecd-e111-bb59-0022644237b5