astro/gpxloggerd: Unbreak on DragonFly
The latest commits broke this port on DragonFly.  The port uses the
base mk files rather than a standalone makefile, and will not build
without warnings appearing:

  gpxloggerd.c:185:16: error: variable 'pt' set but not used
                       [-Werror=unused-but-set-variable]

To ensure -Werror flag is not passed to the build, set NO_WERROR for
the makefile.

Approved by:	blanket (-Werror, restore DF)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@388665 35697150-7ecd-e111-bb59-0022644237b5