Fix check-stagedir plist warning.
https://jenkins.freebsd.org/pci/head-amd64/logs/bulk/headamd64-default/708/logs/errors/motion-3.2.12_4.log
Error: Orphaned: %%ETCDIR%%.conf

This was caused by motion.conf being installed by the Makefile when it
should have been handled only in pkg-plist.

Also switched pkg-plist to use the new @sample keyword.

Submitted by:	swills


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@353290 35697150-7ecd-e111-bb59-0022644237b5