Fix audio/liblo build with clang 3.5.0
On 64-bit arches, audio/liblo will fail to compile with clang 3.5.0, due
to the following -Werror warning:

message.c:1000:17: error: absolute value function 'abs' given an argument of type 'long' but has parameter of type 'int' which may cause truncation of value [-Werror,-Wabsolute-value]
                abs((char *) d - (char *) end), m);
                ^

On 64-bit arches, pointer differences are usually longs, but simply
replacing the abs() call with labs() is also not a good solution,
because then the code is incorrect for 32-bit arches.

Fix this by using a ternary operator expression, which is type-safe.
While here, fix the printf format conversion specifier for printing
ptrdiff_t's.

Approved by: portmgr (antoine)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@373852 35697150-7ecd-e111-bb59-0022644237b5