Mk/Uses/cargo.mk: Fix install for Rust 2018 edition applications
`cargo install` currently fails with:

error: Using `cargo install` to install the binaries for the package
in current working directory is no longer supported, use `cargo
install --path .` instead.

Also see https://github.com/rust-lang/cargo/issues/5327


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@487583 35697150-7ecd-e111-bb59-0022644237b5