science/paraview: No, it's still broken
A while back, the happily building paraview stopped building because
libGL was updated.  The other ports that suffered breakage for the same
reasons were updated to the latest API.  Paraviews libGL callouts were
never fixed, so this port never should not have had it's BROKEN definition
removed as it was not fixed despite the claim.  It's still breaking on all
platforms including DragonFly on clang, gcc47 and gcc50.  Errors from
FreeBSD look like:

In file included from /wrkdirs/usr/ports/science/paraview/work/ParaView-
  v4.1.0/VTK/Rendering/OpenGL/vtkXOpenGLRenderWindow.cxx:31:
In file included from /usr/local/include/GL/glx.h:333:
/usr/local/include/GL/glxext.h:480:143: error: unknown type name 'GLintptr'
  typedef void ( *PFNGLXCOPYBUFFERSUBDATANVPROC) (Display *dpy, GLXContext
readCtx, GLXContext writeCtx, GLenum readTarget, GLenum writeTarget,
  GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
typedef void ( *PFNGLXCOPYBUFFERSUBDATANVPROC) (Display *dpy, GLXContext
  readCtx, GLXContext writeCtx, GLenum readTarget, GLenum writeTarget,
  GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);
/usr/local/include/GL/glxext.h:480:186: error: unknown type name
  'GLsizeiptr'; did you mean 'GLsizei'?
typedef void ( *PFNGLXCOPYBUFFERSUBDATANVPROC) (Display *dpy, GLXContext
  readCtx, GLXContext writeCtx, GLenum readTarget, GLenum writeTarget,
  GLintptr readOffset, GLintptr writeOffset, GLsizeiptr size);


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@379455 35697150-7ecd-e111-bb59-0022644237b5