audio/pulseaudio: track webrtc-aec upstream default
$ pkg install webrtc-audio-processing
$ make

$ make check-plist
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: lib/pulse-%%PULSE_VERSION%%/modules/libwebrtc-util.so
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

$ make stage-qa
====> Running Q/A tests (stage-qa)
Error: /usr/local/lib/pulse-11.1/modules/libwebrtc-util.so is linked to /usr/local/lib/libwebrtc_audio_processing.so.1 from audio/webrtc-audio-processing but it is not declared as a dependency
Warning: you need LIB_DEPENDS+=libwebrtc_audio_processing.so:audio/webrtc-audio-processing


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@481920 35697150-7ecd-e111-bb59-0022644237b5