benchmarks/super-smack: fix build on GCC architectures
GCC from ports is required:
/usr/local/lib/mysql/libmysqlclient.so: undefined reference to `operator delete(void*, unsigned long)@CXXABI_1.3.9'

Approved by:	mentors (implicit approval)


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@506848 35697150-7ecd-e111-bb59-0022644237b5