Attempt to fix the issue for 10.x, 11.x and head on i386.
networking.o: In function `createClient':
networking.c:(.text+0x189): undefined reference to `__atomic_fetch_add_8'
cc: error: linker command failed with exit code 1 (use -v to see invocation)

Do not bump PORTREVISION since this change affects i386 only what's broken till now.


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@448487 35697150-7ecd-e111-bb59-0022644237b5