Fix check-plist error
====> Checking for pkg-plist issues (check-plist)
===> Parsing plist
===> Checking for items in STAGEDIR missing from pkg-plist
Error: Orphaned: @dir %%DOC_DIR%%
===> Checking for items in pkg-plist which are not in STAGEDIR
===> Error: Plist issues found.
*** Error code 1

Stop.
make: stopped in /usr/ports/textproc/rubygem-cld3


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@490034 35697150-7ecd-e111-bb59-0022644237b5