Mark broken: Fails to compile
/usr/local/include/gstreamer-0.10/gst/gstobject.h:283:3: error: unknown type name 'GStaticRecMutex'

Reported by:	pkg-fallout since august 2013
With hat:	portmgr


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@342141 35697150-7ecd-e111-bb59-0022644237b5