Attempt to fix build. The kmm_ofximport_dialogs target depends on kmymoneysettings.h which is generated by the kmm_settings target.
kmymoney/plugins/ofximport/dialogs/kofxdirectconnectdlg.cpp:19:10: fatal error: 'kmymoneysettings.h' file not found

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@471962 35697150-7ecd-e111-bb59-0022644237b5