Mark broken: Fails to compile
 cc -I. -I/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8 -DPHP_ATOM_INC -I/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/include -I/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/main -I/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8 -I/usr/local/include/php -I/usr/local/include/php/main -I/usr/local/include/php/TSRM -I/usr/local/include/php/Zend -I/usr/local/include/php/ext -I/usr/local/include/php/ext/date/lib -I/usr/local/oracle8-client/rdbms/public -I/usr/local/oracle8-client/rdbms/demo -DHAVE_CONFIG_H -O2 -pipe -fno-strict-aliasing -c /wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c  -fPIC -DPIC -o .libs/oci8_interface.o
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c: In function 'zif_oci_free_descriptor':
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c:173: error: 'filename' undeclared (first use in this function)
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c:173: error: (Each undeclared identifier is reported only once
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c:173: error: for each function it appears in.)
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c:173: error: 'filename_len' undeclared (first use in this function)
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c: In function 'zif_oci_lob_save':
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c:212: error: 'filename' undeclared (first use in this function)
/wrkdirs/usr/ports/databases/php52-oci8/work/php-5.2.17/ext/oci8/oci8_interface.c:212: error: 'filename_len' undeclared (first use in this function)

Reported by:	pkg-fallout since august 2013


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@344009 35697150-7ecd-e111-bb59-0022644237b5