Mark broken: fails to link
cc -O2   -Wl,-E -o yorick main.o yinit.o -L. -L../drat -L../hex   -lyor -L/usr/local/lib -lX11  -lm
yinit.o(.text+0x15): In function `on_launch':
: undefined reference to `y_launch'
yinit.o(.data+0x0): undefined reference to `yk_yor'
*** Error code 1

Reported by:	pkg-fallout since february 2014


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@350277 35697150-7ecd-e111-bb59-0022644237b5