devel/renpy: update to 6.99.11
Changes:	http://www.renpy.org/doc/html/changelog.html#ren-py-6-99-11

Temporarily mark games/katawa-shoujo as BROKEN. Other games may work fine.

  $ katawa-shoujo
  ValueError('list.remove(x): x not in list',)

  Full traceback:
    File "game/ui_settings.rpy", line 2, in script
    File "/usr/local/share/renpy/renpy/ast.py", line 805, in execute
      renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
    File "/usr/local/share/renpy/renpy/python.py", line 1641, in py_exec_bytecode
      exec bytecode in globals, locals
    File "game/ui_settings.rpy", line 21, in <module>
    File "/usr/local/share/renpy/renpy/defaultstore.py", line 91, in __setattr__
      renpy.store._set_script_version(value) # E1101 @UndefinedVariable
    File "renpy/common/00compat.rpy", line 134, in _set_script_version
      config.window_auto_hide.remove("call screen")
    File "/usr/local/share/renpy/renpy/python.py", line 568, in do_mutation
      return method(self, *args, **kwargs)
  ValueError: list.remove(x): x not in list

  While running game code:
    File "game/ui_settings.rpy", line 2, in script
    File "game/ui_settings.rpy", line 21, in <module>
    File "renpy/common/00compat.rpy", line 134, in _set_script_version
      config.window_auto_hide.remove("call screen")
  ValueError: list.remove(x): x not in list


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@421471 35697150-7ecd-e111-bb59-0022644237b5