mail/archivemail: Limit to Python 2.7, level up port compliance
archivemail fails to build with Python 3.x [1]:

    print too_old_error
                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(too_old_error)?

Limit to Python 2.7 accordingly.

While I'm here, level up port compliance:

  - Update COMMENT to match setup.py:description
  - Use distutils/autoplist/concurrent (package uses a setup.py). Remove
    NO_BUILD, do-install target, amend pkg-plist accordingly.
  - Patch setup.py to install man pages in /usr/local not /usr/local/share
  - Add test target to assist QA

PR:		237179 [1]
Reported by:	Helge Oldach <freebsd oldach net> [1]
MFH:		2019Q2


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@498876 35697150-7ecd-e111-bb59-0022644237b5