- Update to version 3.2.4, the latest in 3.x branch.  Versions 4.x are   available, but they do not configure (this might be a red herring,   pending further investigation):     ...     checking for blkid_probe_get_topology... no
    FATAL ERROR: could not find a valid BLKID header.
    Install the Block device ID development package.

- Because DISTNAME is sane now, setting of EXTRACT_SUFX and WRKSRC are
  no longer needed and were dropped
- DESTDIR is now respected by `install-sh' script, which allows to drop
  patching of individual makefiles and `include/buildmacros' file
- All programs are installed under ${LOCALBASE}/sbin now
- This version requires a number of patches to build on FreeBSD, most
  importantly:

    * Use getmntinfo() and extattr_set_fd() APIs instead of Linuxish
      getmntent() and fsetxattr()
    * Rename LIST_HEAD -> XFS_LIST_HEAD macro to avoid clash with our
      own one provided by queue(3)
    * Disable missing mremap(2) system call support in `io/mmap.c'
    * Replace `dirent->d_off' with more portable call to telldir()
    * Add missing `#include <inttypes.h>' in several files, etc.

TIMESTAMP (xfsprogs-3.2.4.tar.gz) = 1438219249


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@440701 35697150-7ecd-e111-bb59-0022644237b5