Mark BROKEN: missing header
In file included from actions/activepointadd.cpp:34:
../../src/synfigapp/canvasinterface.h:34:10: fatal error: 'sigc++/object.h' file not found
#include <sigc++/object.h>

Reported by:	pkg-fallout


git-svn-id: svn+ssh://svn.freebsd.org/ports/head@441259 35697150-7ecd-e111-bb59-0022644237b5